begin;

CREATE TABLE public.env_unit_categories
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT env_unit_categories_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.env_unit_categories
    OWNER to postgres;

alter table env_unit_types
drop category;

alter table env_unit_types
add column category_id smallint;

alter table env_unit_types
add constraint fk_env_unit_categories
foreign key (category_id)
references env_unit_categories (id);

insert into env_unit_categories(name) select 'Деталь';
insert into env_unit_categories(name) select 'Прибор';

update env_unit_types set category_id = (select id from env_unit_categories where name = 'Деталь') where name = 'Подшипник';
update env_unit_types set category_id = (select id from env_unit_categories where name = 'Прибор') where name = 'Датчик';

commit;

/*
begin;

alter table env_unit_types
drop constraint fk_env_unit_categories;

alter table env_unit_types
drop category_id;

alter table env_unit_types
add column category varchar(30);

drop table env_unit_categories;

commit;
*/