begin;

CREATE TABLE public.env_unit_oper_names
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT env_unit_oper_names_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.env_unit_oper_names
    OWNER to postgres;

alter table env_unit_opers
drop name;

alter table env_unit_opers
add column name_id smallint;

alter table env_unit_opers
add constraint fk_env_unit_oper_names
foreign key (name_id)
references env_unit_oper_names (id);

insert into env_unit_oper_names(name) select 'Поступление';
insert into env_unit_oper_names(name) select 'Установка';
insert into env_unit_oper_names(name) select 'Поверка';
insert into env_unit_oper_names(name) select 'Замена';
insert into env_unit_oper_names(name) select 'Подтверждение';
insert into env_unit_oper_names(name) select 'Списание';

commit;

/*
begin;

alter table env_unit_opers
drop constraint fk_env_unit_oper_names;

alter table env_unit_opers
drop name_id;

alter table env_unit_opers
add column name varchar(30);

drop table env_unit_oper_names;

commit;
*/